apiVersion: v1
kind: Namespace
metadata:
  name: system
  labels:
    app.kubernetes.io/managed-by: xccelera
    layer: system
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    app.kubernetes.io/managed-by: xccelera
    layer: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai
  labels:
    app.kubernetes.io/managed-by: xccelera
    layer: ai
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    app.kubernetes.io/managed-by: xccelera
    layer: data
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/managed-by: xccelera
    layer: monitoring
